name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs the pipeline when code is pushed to the main branch

jobs:
  print-date:
    runs-on: ubuntu-latest  # Executes on Ubuntu

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Fetches the latest code

      - name: Print Current Date
        run: date  # Prints the current system date and time
